### ISSUE TITLE
Name `some-function` is already taken

### ISSUE THREAD

**Issue by gilbh** [treykeown/arguably#19]
Running Python 3.10 on Windows 10. I tried running the example code:
```
#!/usr/bin/env python3
import arguably

@arguably.command
def some_function(required, not_required=2, *others: int, option: float = 3.14):
    """
    this function is on the command line!

    Args:
        required: a required argument
        not_required: this one isn't required, since it has a default value
        *others: all the other positional arguments go here
        option: [-x] keyword-only args are options, short name is in brackets
    """
    print(f"{required=}, {not_required=}, {others=}, {option=}")

if __name__ == "__main__":
    arguably.run()
```

-- but when I tun it with `-h` I get the following error:
```
ArguablyException: (C:\Dropbox\Documents_and_Writings\Research\Digital_Humanities\Python\kill_file_processes\test_arguably.py:6) some_function: Name `some-function` is already taken
```

Thanks!

**Comment by treykeown** [comment]
Hey, thanks for letting me know!

That's odd - I can't think of any reason why this wouldn't work. I ran this myself without issue on Windows 11 / Python 11 just now.

```
C:\...> py example.py -h
usage: example.py [-h] [-x OPTION] required [not-required] [others ...]

this function is on the command line!

positional arguments:
  required             a required argument (type: str)
  not-required         this one isn't required, since it has a default value (type: int, default: 2)
  others               all the other positional arguments go here (type: int)

options:
  -h, --help           show this help message and exit
  -x, --option OPTION  keyword-only args are options, short name is in brackets (type: float, default: 3.14)
```
```
C:\...> py -m arguably example.py some-function -h
usage: example some-function [-h] [-x OPTION] required [not-required] [others ...]

this function is on the command line!

positional arguments:
  required             a required argument (type: str)
  not-required         this one isn't required, since it has a default value (type: int, default: 2)
  others               all the other positional arguments go here (type: int)

options:
  -h, --help           show this help message and exit
  -x, --option OPTION  keyword-only args are options, short name is in brackets (type: float, default: 3.14)
```

Can you share exactly how you're running this?

**Comment by gilbh** [comment]
Interesting!

I run my python apps on a terminal window inside Neovim, using IPython. And indeed, turns out the culprit is IPython: when I run the traditional --
```
python -m test_arguably
```

-- it is fine.

So, have you tested in IPython? Wondering if there's a more specific platform/version here or not.

Thanks again!

**Comment by treykeown** [comment]
I see. I'm afraid I can't copy your Neovim + IPython setup, but does it happen to keep variables and global state around between runs? My guess is that that's what's happening. When `arguably`'s global state is kept around, and you run these lines again:

```
@arguably.command
def some_function(required, not_required=2, *others: int, option: float = 3.14):
    ...
```

`arguably` will try to re-register this function, which will fail because it has the same name as, well, itself.

FWIW, I was able to run in IPython, though I believe IPython is really only meant to be used interactively.

```
C:\...> C:\...\ipython.exe .\example.py asdf 0 1 2 3
required='asdf', not_required=0, others=(1, 2, 3), option=3.14
```

I'm afraid I'm still confused at your setup - can you provide details of how your setup works? I really only designed `arguably` to be used for scripts you run from the command prompt, or from something that acts like a command prompt.

**Comment by gilbh** [comment]
Ah! 

So, mystery solved. Indeed, when I run the test with the `-h` switch in IPython for the first time, it runs perfectly! 

It is only in repeated runs that things fail b/c of the global state.

As for my workflow: first off, this has no effect on the above. The issues described here occur both in command line and in the nvim terminal. So I am 100% okay with how `arguably` works (although you might wish to correct this behavior, or post a comment on it in the README to clear the issue for those who debug their app in a persistent environment.

I use nvim and in my .vimrc I have the following autocommand:
```
autocmd VimEnter *.py call Start_terminal_and_ipython()
```
What `Start_terminal_and_ipython()` basically does is open a vertical terminal window (I use @milanglacier/yarepl.nvim). The vertical window opens with a command line, to which I then send an execute order to run IPython. This way I can write code and debug with `ipdb`. The setup looks like this:
![image](https://github.com/treykeown/arguably/assets/39532610/2fba5384-5de7-4c82-b5ce-9a3e6b53ae1e)

I have a series of mappings to control the IPython environment, like `%run ...` etc., including debug commands like `next`.

Hope it makes sense to you. 

Thanks for the quick responses!

-- so python files open in my nvim like this:

**Comment by treykeown** [comment]
Gotcha! Thanks for the explanation.

I just looked at the code to see if there's a way to gracefully handle cases like this. I have some ideas, but it would require quite a bit of work.

For now, the best way to work around this is to do what I do in the unit tests - reset the global state by calling

```python
arguably._context.context.reset()
```

Placing this at the very top of your script (before any `@arguably.command` or `@arguably.subtype` decorators) will ensure the global state is reset.

I don't recommend calling this in most cases, as it isn't a supported part of the API, but it should help with your use case.

See #23

**Comment by gilbh** [comment]
I see. Yes, I will keep this in mind when testing etc.

BTW, `arguably` just passed @Nuitka/Nuitka compilation, so now this is truly a CLI command ...

Thanks!

**Comment by treykeown** [comment]
Haha, that's awesome!

Thanks for reaching out. Going to close this now, tracking changes to make global state a bit more graceful in #23
